# Pydantic模式层：请求/响应数据验证
from app.schemas.user import (
    SendVerifyCodeRequest,
    RegisterByPhoneRequest,
    RegisterByEmailRequest,
    LoginByPasswordRequest,
    LoginByVerifyCodeRequest,
    LoginResponse,
    RefreshTokenRequest,
    UserInfoResponse,
    UpdateUserInfoRequest,
    ChangePasswordRequest,
    ResetPasswordRequest,
    BindPhoneRequest,
    BindEmailRequest,
)
from app.schemas.admin import (
    AdminRegisterByPhoneRequest,
    AdminRegisterByEmailRequest,
    AdminLoginByPasswordRequest,
    AdminLoginByVerifyCodeRequest,
    AdminLoginResponse,
    AdminInfoResponse,
    UpdateAdminInfoRequest,
    ChangeAdminPasswordRequest,
    CreateAdminRequest,
    AdminListQuery,
    UpdateAdminRequest,
    ResetAdminPasswordRequest,
    UserListQuery,
    UpdateUserStatusRequest,
    UserDetailResponse,
)
from app.schemas.question import (
    SolveQuestionFromImageRequest,
    SolveQuestionFromTextRequest,
    SolveQuestionResponse,
    AvailableProvidersResponse,
)

__all__ = [
    # User
    "SendVerifyCodeRequest",
    "RegisterByPhoneRequest",
    "RegisterByEmailRequest",
    "LoginByPasswordRequest",
    "LoginByVerifyCodeRequest",
    "LoginResponse",
    "RefreshTokenRequest",
    "UserInfoResponse",
    "UpdateUserInfoRequest",
    "ChangePasswordRequest",
    "ResetPasswordRequest",
    "BindPhoneRequest",
    "BindEmailRequest",
    # Admin
    "AdminRegisterByPhoneRequest",
    "AdminRegisterByEmailRequest",
    "AdminLoginByPasswordRequest",
    "AdminLoginByVerifyCodeRequest",
    "AdminLoginResponse",
    "AdminInfoResponse",
    "UpdateAdminInfoRequest",
    "ChangeAdminPasswordRequest",
    "CreateAdminRequest",
    "AdminListQuery",
    "UpdateAdminRequest",
    "ResetAdminPasswordRequest",
    "UserListQuery",
    "UpdateUserStatusRequest",
    "UserDetailResponse",
    # Question
    "SolveQuestionFromImageRequest",
    "SolveQuestionFromTextRequest",
    "SolveQuestionResponse",
    "AvailableProvidersResponse",
]
