"""add admin logs table

Revision ID: 999cc7c8f711
Revises: 9e15752de4fc
Create Date: 2025-12-25 16:37:18.227793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '999cc7c8f711'
down_revision: Union[str, None] = '9e15752de4fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 创建 admin_logs 表
    op.create_table(
        'admin_logs',
        sa.Column('id', sa.BigInteger(), nullable=False, autoincrement=True),
        sa.Column('admin_id', postgresql.UUID(), nullable=True, comment='管理员ID'),
        sa.Column('admin_username', sa.String(length=64), nullable=False, comment='管理员用户名'),
        sa.Column('log_level', sa.String(length=20), nullable=False, comment='日志级别'),
        sa.Column('module', sa.String(length=50), nullable=False, comment='所属模块'),
        sa.Column('action', sa.String(length=200), nullable=False, comment='操作'),
        sa.Column('description', sa.Text(), nullable=True, comment='操作描述'),
        sa.Column('request_method', sa.String(length=10), nullable=True, comment='HTTP请求方法'),
        sa.Column('request_path', sa.String(length=500), nullable=True, comment='请求路径'),
        sa.Column('request_params', postgresql.JSONB(), nullable=True, comment='请求参数'),
        sa.Column('ip_address', postgresql.INET(), nullable=True, comment='IP地址'),
        sa.Column('user_agent', sa.Text(), nullable=True, comment='User-Agent'),
        sa.Column('status_code', sa.Integer(), nullable=True, comment='HTTP状态码'),
        sa.Column('is_success', sa.Boolean(), nullable=False, server_default=sa.text('true'), comment='是否成功'),
        sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
        sa.Column('response_time_ms', sa.Integer(), nullable=True, comment='响应时间(毫秒)'),
        sa.Column('extra_data', postgresql.JSONB(), nullable=True, comment='额外数据'),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_logs_admin_id', 'admin_logs', ['admin_id'])
    op.create_index('ix_admin_logs_log_level', 'admin_logs', ['log_level'])
    op.create_index('ix_admin_logs_module', 'admin_logs', ['module'])
    op.create_index('ix_admin_logs_created_at', 'admin_logs', ['created_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_logs_created_at', table_name='admin_logs')
    op.drop_index('ix_admin_logs_module', table_name='admin_logs')
    op.drop_index('ix_admin_logs_log_level', table_name='admin_logs')
    op.drop_index('ix_admin_logs_admin_id', table_name='admin_logs')
    op.drop_table('admin_logs')
    # ### end Alembic commands ###
    # ### end Alembic commands ###

